modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/urushi-mod"
updateJSONURL="https://raw.githubusercontent.com/iwaliner/Urushi-MOD-1.20.1/main/updates.json"
logoFile="logo.png"

authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[modproperties.${mod_id}]
    catalogueItemIcon="urushi:kasuga_lantern"
